#################
## Controllers ##
#################
dh_ag95:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      finger_joint:
        type: position_controllers/GripperActionController
        joint: ag95_finger_joint
        goal_tolerance: 0.001
        stall_timeout: 1.0
