#################
## Controllers ##
#################
AG95:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      finger_joint:
        type: position_controllers/GripperActionController
        joint: AG95_finger_joint
